#define Esc       0xefff       //a - new
#define Enter     0x7fff       //d
#define BackSp    0xf7ff       //#
#define GrPlus    0xdfff       //b
#define GrMinus   0xbfff       //c
#define Num7      0xfffb //1 - old
#define Num8      0xffbf //2
#define Num9      0xfbff //3
#define Num4      0xfffd
#define Num5      0xffdf
#define Num6      0xfdff
#define Num1      0xfffe //7
#define Num2      0xffef //8
#define Num3      0xfeff //9
#define Point     0xfff7 //0->*(=.)
#define Num0      0xff7f //.->0
#define CtrlPlus  0xdff7
#define CtrlMinus 0xbff7
#define AltX      0xf3ff
#define Ctrl9     0xdffb
#define CtrAD     0xeff9
#define Ctrl1     0xfff6
#define Ctrl2     0xffe7
#define Ctrl3     0xfef7
#define Ctrl4     0xfff5
#define Ctrl0     0xff77
#define CtrlBs    0xf7f7
